/** JSONTree theme driven by global CSS tokens */
export const jsonTheme = {
	scheme: "genum",
	base00: "hsl(var(--card))",
	base01: "hsl(var(--surface-muted))",
	base02: "hsl(var(--muted))",
	base03: "hsl(var(--muted-foreground))",
	base04: "hsl(var(--muted-foreground) / 0.85)",
	base05: "hsl(var(--foreground))",
	base06: "hsl(var(--foreground) / 0.9)",
	base07: "hsl(var(--foreground))",
	base08: "hsl(var(--brand))",
	base09: "hsl(var(--brand))",
	base0A: "hsl(var(--brand))",
	base0B: "hsl(var(--brand))",
	base0C: "hsl(var(--brand))",
	base0D: "hsl(var(--brand))",
	base0E: "hsl(var(--brand))",
	base0F: "hsl(var(--brand))",
};
